const countries = [
  "Afghanistan",
  "Albanien",
  "Algerien",
  "Amerikanisch-Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarktis",
  "Antigua und Barbuda",
  "Argentinien",
  "Armenien",
  "Aruba",
  "Australien",
  "Österreich",
  "Aserbaidschan",
  "Bahamas (die)",
  "Bahrain",
  "Bangladesch",
  "Barbados",
  "Weißrussland",
  "Belgien",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivien (Plurinationaler Staat)",
  "Bonaire, Sint Eustatius und Saba",
  "Bosnien und Herzegowina",
  "Botswana",
  "Bouvetinsel",
  "Brasilien",
  "Britisches Territorium im Indischen Ozean (das)",
  "Brunei Darussalam",
  "Bulgarien",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Kambodscha",
  "Kamerun",
  "Kanada",
  "Kaimaninseln (die)",
  "Zentralafrikanische Republik (die)",
  "Tschad",
  "Chile",
  "China",
  "Weihnachtsinsel",
  "Kokosinseln (Keeling) (die)",
  "Kolumbien",
  "Komoren (die)",
  "Kongo (die)",
  "Kongo (Demokratische Republik)",
  "Kongo (die)",
  "Cookinseln (die)",
  "Costa Rica",
  "Kroatien",
  "Kuba",
  "Curaçao",
  "Zypern",
  "Tschechien",
  "Côte d'Ivoire",
  "Dänemark",
  "Dschibuti",
  "Dominica",
  "Dominikanische Republik (die)",
  "Ecuador",
  "Ägypten",
  "El Salvador",
  "Äquatorialguinea",
  "Eritrea",
  "Estland",
  "Eswatini",
  "Äthiopien",
  "Falklandinseln (die) [Malwinen]",
  "Färöer Inseln (die)",
  "Fidschi",
  "Finnland",
  "Frankreich",
  "Französisch-Guayana",
  "Französisch-Polynesien",
  "Französische Südterritorien",
  "Gabun",
  "Gambia (die)",
  "Georgien",
  "Deutschland",
  "Ghana",
  "Gibraltar",
  "Griechenland",
  "Grönland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island und McDonald Islands",
  "Heiliger Stuhl (der)",
  "Honduras",
  "Hongkong",
  "Ungarn",
  "Island",
  "Indien",
  "Indonesien",
  "Iran (Islamische Republik)",
  "Irak",
  "Irland",
  "Isle of Man",
  "Israel",
  "Italien",
  "Jamaika",
  "Japan",
  "Jersey",
  "Jordanien",
  "Kasachstan",
  "Kenia",
  "Kiribati",
  "Korea (Demokratische Volksrepublik)",
  "Korea (die Republik)",
  "Kuwait",
  "Kirgisistan",
  "Demokratische Volksrepublik Laos (die)",
  "Lettland",
  "Libanon",
  "Lesotho",
  "Liberia",
  "Libyen",
  "Liechtenstein",
  "Litauen",
  "Luxemburg",
  "Macao",
  "Madagaskar",
  "Malawi",
  "Malaysia",
  "Malediven",
  "Mali",
  "Malta",
  "Marshallinseln (die)",
  "Martinique",
  "Mauretanien",
  "Mauritius",
  "Mayotte",
  "Mexiko",
  "Mikronesien (Föderierte Staaten von)",
  "Moldawien (die Republik)",
  "Monaco",
  "Mongolei",
  "Montenegro",
  "Montserrat",
  "Marokko",
  "Mosambik",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Niederlande (die)",
  "Neukaledonien",
  "Neuseeland",
  "Nicaragua",
  "Niger (der)",
  "Nigeria",
  "Niue",
  "Norfolkinsel",
  "Nördliche Marianen (die)",
  "Norwegen",
  "Oman",
  "Pakistan",
  "Palau",
  "Palästina, Staat",
  "Panama",
  "Papua-Neuguinea",
  "Paraguay",
  "Peru",
  "Philippinen (die)",
  "Pitcairn",
  "Polen",
  "Portugal",
  "Puerto Rico",
  "Katar",
  "Republik Nordmazedonien",
  "Rumänien",
  "Russische Föderation (die)",
  "Ruanda",
  "Réunion",
  "St. Barthélemy",
  "St. Helena, Ascension und Tristan da Cunha",
  "St. Kitts und Nevis",
  "St. Lucia",
  "St. Martin (französischer Teil)",
  "St. Pierre und Miquelon",
  "St. Vincent und die Grenadinen",
  "Samoa",
  "San Marino",
  "Sao Tome und Principe",
  "Saudi-Arabien",
  "Senegal",
  "Serbien",
  "Seychellen",
  "Sierra Leone",
  "Singapur",
  "Sint Maarten (niederländischer Teil)",
  "Slowakei",
  "Slowenien",
  "Salomonen",
  "Somalia",
  "Südafrika",
  "Südgeorgien und die Südlichen Sandwichinseln",
  "Südsudan",
  "Spanien",
  "Sri Lanka",
  "Sudan (der)",
  "Surinam",
  "Svalbard und Jan Mayen",
  "Schweden",
  "Schweiz",
  "Syrische Arabische Republik",
  "Taiwan",
  "Tadschikistan",
  "Tansania, Vereinigte Republik",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad und Tobago",
  "Tunesien",
  "Türkei",
  "Turkmenistan",
  "Turks- und Caicosinseln (die)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "Vereinigte Arabische Emirate (die)",
  "Vereinigtes Königreich von Großbritannien und Nordirland (the)",
  "United States Minor Outlying Islands (the)",
  "Vereinigte Staaten von Amerika (die)",
  "Uruguay",
  "Usbekistan",
  "Vanuatu",
  "Venezuela (Bolivarische Republik)",
  "Vietnam",
  "Jungferninseln (Britisch)",
  "Jungferninseln (U.S.)",
  "Wallis und Futuna",
  "Westsahara",
  "Jemen",
  "Sambia",
  "Simbabwe",
  "Åland-Inseln",
];

const countriesDE = countries.sort((a, b) =>
  a.localeCompare(b, "de", { sensitivity: "base" })
);
console.dir(countriesDE, { maxArrayLength: null });
