module.exports.materials = [
  "AFK",
  "ASA",
  "Accura 25",
  "Accura Xtreme",
  "Acryl (PIMMA)",
  "Advanced Materials",
  "Alpha / Beta Titan",
  "Aluminium",
  "Aluminiumoxid",
  "Automatenstahl",
  "Balkenschichtholz",
  "Bustahl",
  "Brettschichtholz",
  "Brettsperrholz",
  "CFK",
  "Composites",
  "Derlin 100",
  "Diamanten",
  "Duroplaste",
  "Edel- und Halbedelsteine",
  "Edelstahl (rostfrei V2A)",
  "Edelstahl (Rostfrei/säurebeständige V4A)",
  "Einsatz-/Vergütungsstahl",
  "Elastomere",
  "Ehtafoam 220",
  "Federstahl",
  "Flachpressplatte",
  "Formvollholz",
  "Furnierschichtholz",
  "Furniersperrholz",
  "Furnierstreifenholz",
  "GFK",
  "GMC",
  "Gestein",
  "Gips",
  "Gipsfaserplatte",
  "Gibsgebundene Spanplatte",
  "Glas/Mineralische Stoffe",
  "Glaskeramin/Lithium-Disilikat",
  "Gold",
  "Graphit",
  "Grauguss",
  "Gusseisen",
  "HIPS",
  "Hartmetalle",
  "Hochdichte Holzfaserplatte (HDF)",
  "Hochleistungskunststoffe",
  "Holzwolle-Leichtbauplatte",
  "Kaltfließpressstahl/Kautschuk und Gummi",
  "Keramik",
  "Kobalt-Chrom",
  "Korund",
  "Kunstharz-Pressholz",
  "Kupfer und Kupferlegierung",
  "Kupfer-Zink-Legierung",
  "LSR",
  "Lote",
  "Magnesium",
  "Mehrschichtplatte",
  "Messing",
  "Metalle",
  "Mineralguss",
  "Mitteldichte Holzfaserplatte (MDF)",
  "Molybdän",
  "NFK",
  "Nickelbasislegierungen",
  "Nickellegierungen (Inconel)",
  "Monel",
  "Hastelloy)",
  "Nylon 6",
  "Nylon 6.6",
  "OBJET VeroBlue",
  "OSB-Platte",
  "Optisches Glas",
  "Oxidkeramik",
  "PA",
  "PA 6",
  "PA 6.6",
  "PA-GB",
  "PA12",
  "PC",
  "PC-ISO",
  "PEEK",
  "PEI",
  "PETG",
  "PHA",
  "PLA",
  "POM",
  "PP",
  "PROJET Techplast",
  "PVA",
  "PVC",
  "Par 21/G",
  "Platin",
  "Ployjet Tango",
  "Ployjet Vero",
  "Polymergips",
  "Prssvollholz",
  "Quarzglas",
  "Rene 41",
  "Resin",
  "Rubin",
  "SLA",
  "ST-130",
  "Spahir",
  "Silber",
  "Silizium",
  "Siliziumkarbid",
  "Siliziumnitrid",
  "Somos PerFORM",
  "Somos ProtoTherm",
  "Somos WaterClear",
  "Sonstige",
  "Spanstreifenholz",
  "Sperrholz",
  "Stabsperrholz",
  "Stacks",
  "Stahl",
  "Stahlguss",
  "Strangpressplatte",
  "Stäbchensperrholz",
  "TPE",
  "TPU",
  "Teilchenverstärkte Verbundwerkstoffe",
  "Thermoplaste",
  "Titan",
  " Titanaluminid",
  "Titan-Keramik-Pulver",
  "Tränkvollholz",
  "ULTEM",
  "ULTEM 1010 CG",
  "ULTEM 9085",
  "Ureol",
  "Verbundplatte",
  "Vollholz (Massivholz)",
  "WPC",
  "Weiche Holzfaserplatte",
  "Werkzeugstahl",
  "Wolfram",
  "Zementgebundene Spanplatte",
  "Zerodur",
  "Zink und Zinklegierung",
  "Zirkonoxid",
];
module.exports.technologies = [
  "3-Achs-CNC-Fräsen",
  "5-Achs-CNC-Fräsen",
  "Abkanten",
  "Additive Fertigung / 3D Druck",
  "Auftragschweißen",
  "Beschichten",
  "Binding Jetting (BJ)",
  "Bohren",
  "Bürsten",
  "Digital Light Processing (DLP)",
  "Direct Metal Laser Sintering (DMLS)",
  "Drechseln",
  "Drehen",
  "Drop on Demond (DOD)",
  "Einpressen",
  "Elektronenstrahl-Schmelzen",
  "Erodieren (EDM)",
  "Falzen",
  "Flachschleifen",
  "Fräsen",
  "Furnierbearbeitung",
  "Fused Deposition Modeling (FDM)",
  "Hobeln",
  "Hohlnieten",
  "Hybrid-Prozesse (HP)",
  "Kaltumformen",
  "Kantenbearbeitung",
  "Kantenleimen",
  "Kleben",
  "Laser",
  "Laser Melting (LM)",
  "Laserschneiden",
  "Laserschweißen",
  "Lasersintern (LS)",
  "Laserstrahl-Schmelzen",
  "Material Binder Jetting (MJ)",
  "Metal Binder Jetting",
  "Multi Jet Fusion (MJF)",
  "Multijet-Technologie",
  "Nieten",
  "Photopolymer Jetting (PJ)",
  "Plasmaschneiden",
  "Polyjet-Technologie",
  "Pressen",
  "Reiben",
  "Richten",
  "Runden/ Biegen",
  "Rundschleifen",
  "Sand Binder Jetting",
  "Scheren",
  "Schleifen",
  "Schweißen",
  "Selektives Lasersintern (SLS)",
  "Selektives Laserstrahl-Schmezlen",
  "Senken",
  "Sicken",
  "Sonstige",
  "Stanzen",
  "Stemmen",
  "Stereolithografie (STL / SLA)",
  "Sägen (Zuschnitt)",
  "Tiefziehen",
  "Ultraschall-Bearbeitung",
  "Voxeljet-Technologie",
  "Walzen",
  "Wasserstrahlschneiden",
  "Werkzeug Schleifen",
];
module.exports.certificates = [
  "AS9100",
  "DIN 18800-7:2008 Klasse A-C (kl. Schweißnachweis)",
  "DIN 18800-7:2008 Klasse D/E (gr. Schwei0nachweis)",
  "DIN 4113",
  "DIN 6701",
  "DIN EN 1090",
  "DIN EN ISO 3834",
  "EN 15085",
  "EN 9100",
  "EN ISO 13485",
  "FFL Class 10",
  "FFL Class 6",
  "FFL Class 7",
  "FSC",
  "IATF 16949",
  "ISO 14001",
  "ISO 9001",
  "ISO 9001:2008",
  "ISO 9001:2015",
  "ISO-TS 16949:2002",
  "ISO-TS 16949:2009",
  "JAR 145",
  "OHSAS 18000",
  "PART 145",
  "PEFC",
  "QSF-A",
  "QSF-B",
  "SA 8000",
  "PART 145",
  "PEFC",
  "QSF-A",
  "QSF-B",
  "SA 8000",
  "VDA 6.1",
  "VDA 6.2",
];

module.exports.languages =
[
  "Bahasa Indonesia",
  "Bahasa Malaysia",
  "Bengali",
  "Dansk",
  "Deutsch",
  "English",
  "Español",
  "Français",
  "Hindi",
  "Italiano",
  "Magyar",
  "Nederlands",
  "Norsk",
  "Polski",
  "Português",
  "Punjabi",
  "Sign Language",
  "Suomi",
  "Svenska",
  "Tagalog",
  "Türkçe",
  "Čeština",
  "Ελληνικά",
  "Русский",
  "українська",
  "עברית",
  "العربية",
  "ภาษาไทย",
  "中文",
  "日本語",
  "한국어",
]